"""Initial migration

Revision ID: 4e9b37eedbac
Revises: 
Create Date: 2024-07-08 15:16:33.246910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9b37eedbac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('sub_category', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=255), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_config')
    op.drop_table('company_data')
    # ### end Alembic commands ###
